name: build-and-test
on:
  push:
    branches:
      - 9.x-dev

jobs:
  build-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: assets
          path: Resources/Public/JavaScript

  php-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - run: composer install
      - run: composer run ci:php:lint

  php-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - run: composer install
      - run: composer run ci:php:fixer

  php-stan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - run: composer install
      - run: composer run ci:php:stan

  version-check:
    runs-on: ubuntu-latest
    needs:
      - build-assets
      - php-lint
      - php-fixer
      - php-stan
    outputs:
      latest-version: ${{ steps.main.outputs.latest-version }}
      typo3-ext-version: ${{ steps.dev.outputs.typo3-ext-version }}
    steps:
      - uses: actions/checkout@v3
      - id: dev
        run: |
          TYPO3_EXT_VERSION=$(cat ext_emconf.php | grep "version*" | grep -Po "(\d+\.)+\d+")
          echo "::set-output name=typo3-ext-version::$(echo ${TYPO3_EXT_VERSION})"
      - uses: actions/checkout@v3
        with:
          ref: 9.x
      - run: git fetch --prune --unshallow --tags
      - id: main
        run: |
          LATEST_TAG=$(git describe --abbrev=0 --tags | grep -Po "(\d+\.)+\d+")
          echo "::set-output name=latest-version::$(echo ${LATEST_TAG})"

  release:
    runs-on: ubuntu-latest
    needs:
      - version-check
    if: ${{ needs.version-check.outputs.latest-version != needs.version-check.outputs.typo3-ext-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: git checkout -b release-${{needs.version-check.outputs.typo3-ext-version}} 9.x-dev
      - name: Download assets
        uses: actions/download-artifact@v3
        with:
          name: assets
          path: Resources/Public/JavaScript
      - name: Clean up
        run: rm -rf .ddev .github config Configuration/php-cs-fixer.php node_modules public var vendor typo3_src .editorconfig .gitignore .phpstorm.meta.php package.json package-lock.json phpstan.neon phpstan-baseline.neon tsconfig.json webpack.js
      - uses: EndBug/add-and-commit@v9
        id: commit
        with:
          add: '.'
          committer_name: GitHub Actions
          committer_email: actions@github.com
          message: 'build: ${{needs.version-check.outputs.typo3-ext-version}}'
          new_branch: release-${{needs.version-check.outputs.typo3-ext-version}}
      - name: Create PR
        id: pr
        run: |
          PR_URL=$(gh pr create --title="Release ${{needs.version-check.outputs.typo3-ext-version}}" --body 'build ${{ steps.commit.commit_sha }}' --base 9.x --head release-${{needs.version-check.outputs.typo3-ext-version}})
          echo "::set-output name=pr-url::$(echo ${PR_URL})"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Merge PR
        run: gh pr merge ${{ steps.pr.pr-url }} -d -s
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: "v${{needs.version-check.outputs.typo3-ext-version}}"

