name: build-and-test
on:
  push:
    branches:
      - dev

jobs:
  build-assets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm install
      - run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: assets
          path: |
            Resources/Public/JavaScript

  php-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - run: composer install
      - run: composer run ci:php:lint

  php-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - run: composer install
      - run: composer run ci:php:fixer

  php-stan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
      - run: composer install
      - run: composer run ci:php:stan

  version-check:
    runs-on: ubuntu-latest
    needs:
      - build-assets
      - php-lint
      - php-fixer
      - php-stan
    outputs:
      latest-version: ${{ steps.main.outputs.latest-version }}
      typo3-ext-version: ${{ steps.dev.outputs.typo3-ext-version }}
    steps:
      - uses: actions/checkout@v2
      - id: dev
        run: |
          TYPO3_EXT_VERSION=$(cat ext_emconf.php | grep "version*" | grep -Po "(\d+\.)+\d+")
          echo "::set-output name=typo3-ext-version::$(echo ${TYPO3_EXT_VERSION})"
      - uses: actions/checkout@v2
        with:
          ref: main
      - run: git fetch --prune --unshallow --tags
      - id: main
        run: |
          LATEST_TAG=$(git describe --abbrev=0 --tags | grep -Po "(\d+\.)+\d+")
          echo "::set-output name=latest-version::$(echo ${LATEST_TAG})"

  release:
    runs-on: ubuntu-latest
    needs:
      - version-check
    if: ${{ needs.version-check.outputs.latest-version != needs.version-check.outputs.typo3-ext-version }}
    steps:
      - uses: actions/checkout@v2
      - run: git checkout -b release-${{needs.version-check.outputs.typo3-ext-version}} dev
      - name: Download assets
        uses: actions/download-artifact@v3
        with:
          name: assets
      - uses: EndBug/add-and-commit@v9
        with:
          add: '*/.*'
          committer_name: GitHub Actions
          committer_email: actions@github.com
          message: '[Build] ${{ env.GITHUB_SHA }}'
      - run: rm -rf .ddev .github config Configuration/php-cs-fixer.php node_modules public var vendor typo3_src .editorconfig .gitignore .phpstorm.meta.php package.json package-lock.json phpstan.neon phpstan-baseline.neon tsconfig.json webpack.js
      - uses: EndBug/add-and-commit@v9
        with:
          add: '*/.*'
          committer_name: GitHub Actions
          committer_email: actions@github.com
          message: '[Build] Clean up'
      - uses: actions/checkout@v2
        with:
          ref: main
      - run: git merge release-${{needs.version-check.outputs.typo3-ext-version}} --log
      - run: git tag -a "v${{needs.version-check.outputs.typo3-ext-version}}" -m ""
      - run: git push origin main --tags
