jobs:
  release:
    uses: maikschneider/reusable-workflows/.github/workflows/release-typo3-extension.yml@main
    secrets:
      teams-webhook-url: ${{ secrets.TEAMS_WEBHOOK_URL }}
    with:
      base-branch: 9.x
      build-assets: true